name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: Install
        run: npm ci

      - name: Test
        run: npm run lint

      - name: Build
        run: npm run build
